sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  # - linux
  - osx

install:
  - yarn global add lix.pm haxeshim
  - lix download

script:
  - haxelib run travix cpp -lib linc_lua # -D mac
  # - haxelib run travix js -lib hxjs-fengari
  - haxelib run travix node -lib hxjs-fengari
