sudo: required
dist: xenial

language: node_js
node_js: 10

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=stable
  - HAXE_VERSION=nightly

  
install:
  - yarn global add lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix cpp -lib linc_lua # -D mac
  # - lix run travix js -lib hxjs-fengari
  - lix run travix node -lib hxjs-fengari
