# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Debug
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - ps: cl.exe
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Install modules
  - npm install -g lix
  - lix download

# Post-install test scripts.
test_script:
  - haxelib run travix cpp -lib linc_lua # -D mac
  # - haxelib run travix js -lib hxjs-fengari
  - haxelib run travix node -lib hxjs-fengari

# Don't actually build.
build: off